// Generated by CoffeeScript 1.3.1
(function() {
  var SectionHeading;

  $(window).ready(function() {
    var heading, headings, section, _i, _len;
    $('.contents').remove();
    headings = $('.section > h1, .section > h2, .section > h3');
    for (_i = 0, _len = headings.length; _i < _len; _i++) {
      heading = headings[_i];
      new SectionHeading($(heading));
    }
    if (window.location.hash) {
      section = $(window.location.hash);
      section.show();
      return section.parents('.section').show();
    }
  });

  SectionHeading = (function() {

    SectionHeading.name = 'SectionHeading';

    function SectionHeading(heading) {
      var anchor,
        _this = this;
      this.heading = heading;
      this.section = this.heading.parent();
      this.heading.addClass('section-heading');
      this.heading.remove().insertBefore(this.section);
      this.section.hide();
      anchor = this.heading.find('a');
      anchor.attr('href', '#' + this.section.attr('id'));
      anchor.click(function(e) {
        e.preventDefault();
        return _this.section.toggle();
      });
    }

    return SectionHeading;

  })();

}).call(this);
