#!/bin/bash

function build {
  file=`echo $1 | sed 's#^\./\?##'`
  html_file=`echo $file | sed 's/\.rst$/.html/'`
  echo "Compiling '$file' to '$html_file'"
  dirname=`dirname $file`
  if [ $dirname != "." ]; then
    dirname=`dirname $file | sed 's#[^/]\+#..#g'`
  fi
  echo "dirname=[$dirname]"
  cat scripts/template.txt | sed "s#%%%ROOT%%%#$dirname#" > scripts/template.txt.tmp
  scripts/rst2html-pygments.py --template=scripts/template.txt.tmp $1 $html_file
  rm scripts/template.txt.tmp
}

if [ "$1" != "" ]; then
  build "$1"
else
  rst_files=`find . -iname '*\.rst' | sort`

  for f in $rst_files; do
    build "$f"
  done
fi

